---
# role: ansible-role-borg-backup
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
  # options:
  #   role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: borg_backup-alpine311
    image: "fgoebel/molecule-alpine:3.11"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: borg_backup-alpine
    image: "fgoebel/molecule-alpine:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: borg_backup-amazonlinux
    image: "fgoebel/molecule-amazonlinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-arch
    image: "fgoebel/molecule-archlinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-centos6
    image: "fgoebel/molecule-centos:6"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: borg_backup-centos7
    image: "fgoebel/molecule-centos:7"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-centos8
    image: "fgoebel/molecule-centos:8"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-debian9
    image: "fgoebel/molecule-debian:9"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-debian10
    image: "fgoebel/molecule-debian:10"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-debian
    image: "fgoebel/molecule-debian:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-opensuse15
    image: "fgoebel/molecule-opensuse:15"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-opensuse
    image: "fgoebel/molecule-opensuse:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-opensuse-tumbleweed
    image: "fgoebel/molecule-opensuse:tumbleweed"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-oraclelinux6
    image: "fgoebel/molecule-oraclelinux:6"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: borg_backup-oraclelinux7
    image: "fgoebel/molecule-oraclelinux:7"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-oraclelinux8
    image: "fgoebel/molecule-oraclelinux:8"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-oraclelinux
    image: "fgoebel/molecule-oraclelinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-ubuntu1604
    image: "fgoebel/molecule-ubuntu:16.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-ubuntu1804
    image: "fgoebel/molecule-ubuntu:18.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-ubuntu2004
    image: "fgoebel/molecule-ubuntu:20.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: borg_backup-ubuntu
    image: "fgoebel/molecule-ubuntu:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        borg_backup_role_enabled: True
verifier:
  name: ansible
