---
extends: default

ignore: |
  cloud-init.yml
  .venv

rules:
  truthy:
    allowed-values:
      - "False"
      - "false"
      - "True"
      - "true"
      - "yes"
      - "no"
  comments-indentation: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
