---
# role: ansible-role-borg-backup
# file ./tasks/binary-install.yml

- name: Check if borg is present already
  stat: 
    path: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
  register: stat_borg_presence

- name: Download borg
  become: yes
  get_url:
    url: "{{ borg_download_url }}"
    dest: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    mode: "0755"

- name: create symlink for borg
  become: yes
  file:
    src: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    dest: "{{ borg_install_path }}/borg"
    state: link
    # force?
    force: yes

- name: create symlink for borgfs
  become: yes
  file:
    src: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    dest: "{{ borg_install_path }}/borgfs"
    state: link
    # force?
    force: yes