---
# role: ansible-role-borg-backup
# file ./tasks/binary-install.yml

- name: fail not supported OS
  fail:
    msg: "Sry i was to lazy to implement force binary installation for this OS. I am really sorry!"
  when: ansible_os_family == "Alpine"

- name: Install packages for ansible-role-borg-backup
  package:
    name: "{{ borg_backup_binary_required_packages }}"
    state: present

- name: Download borg
  become: yes
  get_url:
    url: "{{ borg_download_url }}"
    dest: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    mode: "0755"

- name: create symlink for borg
  become: yes
  file:
    src: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    dest: "{{ borg_install_path }}/borg"
    state: link
    # force?
    force: yes

- name: create symlink for borgfs
  become: yes
  file:
    src: "{{ borg_install_path }}/borg-{{borg_binary_version}}"
    dest: "{{ borg_install_path }}/borgfs"
    state: link
    # force?
    force: yes