---
# role: ansible-role-borg-backup
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Install packages for ansible-role-borg-backup
  package:
    name: "{{ borg_backup_packages }}"
    state: present

- name: include tasks for manual installation with binary package
  include_tasks: binary-install.yml
  when: not borg_backup_package_available
