---
# role: ansible-role-borg-backup
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Install packages for ansible-role-borg-backup
  package:
    name: "{{ borg_backup_packages }}"
    state: present
  when:
    - borg_backup_package_available
    - not borg_force_binary_installation

- name: include tasks for manual installation with binary package
  include_tasks: binary-install.yml
  when: |
    (not borg_backup_package_available)
    or borg_force_binary_installation

- name: Create borg client scripts
  template:
    dest: /usr/local/bin/borg-{{ bc.name }}
    src: borg-backup.sh.j2
    owner: root
    group: root
    mode: '0744'
  loop: "{{ borg_configs }}"
  loop_control:
    loop_var: bc  # short for borg_config
    label: "{{ bc.name }}"
  when: borg_client_config_enabled | bool

# ssh-key-generation and location
# configure ssh-key on backup destination
#   including restrictive access and append only

# server setup and configuration
# - name: configure borg server

# configure ssh options for borg: see https://borgbackup.readthedocs.io/en/stable/usage/serve.html for more information

# backup retries
