---
# role: ansible-role-borg-backup
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  # options:
  #   role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: alpine311-borg-backup
    box: "generic/alpine311"
    cpus: 2
    memory: 1024
  - name: arch-borg-backup
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: centos8-borg-backup
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: debian10-borg-backup
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: fedora33-borg-backup
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: ubuntu1804-borg-backup
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: ubuntu2004-borg-backup
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        borg_backup_role_enabled: True
        bootstrap: true
verifier:
  name: ansible
