---
# role: ansible-role-borg-backup
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  # options:
  #   role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: borg-backup-arch
    box: "archlinux/archlinux"
  - name: borg-backup-centos8
    box: "centos/8"
  - name: borg-backup-debian10
    box: "debian/buster64"
  - name: borg-backup-fedora31
    box: "fedora/31-cloud-base"
  - name: borg-backup-ubuntu1804
    box: "generic/ubuntu1804"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        borg_backup_role_enabled: True
verifier:
  name: ansible
