---
# role:
# file:

- name: Verfy
  hosts: all
  pre_tasks:
    - name: "Include variables to converge playbook"
      include_vars: vars.yml
  tasks:
    # specific to borg.
    # as a python-binary it extracts to /tmp and requires exec on that path
    - name: create new temporary folder for testing borg
      file:
        path: /temp-borg
        mode: "0777"
        state: directory

    - name: run borg --version
      command: "borg --version"
      register: borg_version
      environment:
        TEMP: "/temp-borg"
      changed_when: false

    - name: show installed version
      debug:
        var: borg_version.stdout

    - name: Assert borg is installed and working
      assert:
        that:
          - borg_backup_role_enabled
          - borg_version.rc == 0
      when: not borg_force_binary_installation

    - name: Assert version when force installed
      assert:
        that:
          - borg_backup_role_enabled
          - borg_version.rc == 0
          - borg_version.stdout == "borg 1.1.15"
      when:
        - borg_force_binary_installation
        # Alpine force binary installation will fail... so we exclude these until fixed
        - not ansible_os_family == "Alpine"
